name = "isp-translator"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "ISP_DB"
database_name = "isp-translator-db"
database_id = "f72b6ce7-b8e7-4832-a021-087dcd1833f0"

[ai]
binding = "ISP_AI"

[vars]
# 生产环境 API_TOKEN 通过 secret 管理，本地开发通过 .dev.vars 管理
